# training_dir = "/content/drive/My Drive/data/sign_data/train"
# training_csv = "/content/drive/My Drive/data/sign_data/train_data.csv"
# testing_csv = "/content/drive/My Drive/data/sign_data/test_data.csv"
# testing_dir = "/content/drive/My Drive/data/sign_data/test"
training_dir = "/content/sign_data/train"
training_csv = "/content/sign_data/train_data.csv"
testing_csv = "/content/sign_data/test_data.csv"
testing_dir = "/content/sign_data/test"
batch_size = 32
epochs = 20
